### ISSUE TITLE
Support approximate comparisons using the `approx` crate

### ISSUE THREAD

**Issue by tylerreisinger** [starkat99/half-rs#19]
There are many situations when an approximate comparison is useful for floats. The `approx` crate appears to the the de-facto standard crate supporting standard approximate comparisons, so implementing the traits for `f16` as an optional feature could be a useful addition.

**Comment by starkat99** [comment]
I like the idea of supporting the approx crate in principle, but there's some obstacles that make it less than ideal. Approximate floating point comparisons require both a subtract and abs operator, but no numeric operations are implemented for the f16 type, only basic classification and conversion. This is because there's no hardware support for any of these operations for any of Rust's targets (that I know of) so this would have to be implemented in software, which would likely be less performant than converting to f32 to do operations and then back again (especially if using hardware intrinsics for conversion). Even were we to convert to f32 under the hood (a bad idea to hide that imo), the core rust library does not have an abs operator for f32 or f64 either, so no_std would need to implement that (I admit, this is more trivial to do, but annoying).
