### ISSUE TITLE
support total ordering

### ISSUE THREAD

**Issue by joseluis** [starkat99/half-rs#55]
Rust stabilized in 1.62 the [`total_cmp`](https://doc.rust-lang.org/stable/core/primitive.f32.html#method.total_cmp) method that follows the `totalOrder` predicate from the IEEE754 spec (v2008, 5.10).

The same method could be added easily if it calculated the total order after converting to f32. There could also be `total_cmp` & `total_cmp_const` variants.

If bumping the MSRV to 1.62 is a problem, it'd be also very easy to reimplement it from scratch.

**Comment by starkat99** [comment]
Due to earlier incidents involving bumping MSRV, any changes in MSRV in this crate will require a major version bump, so I'd usually like to avoid unless there's a very clear need. I'd be happy to accept a PR adding a total ordering implementation, I just don't have the time to do it myself right now.
