### ISSUE TITLE
Use 8x SIMD conversions when appropriate

### ISSUE THREAD

**Issue by starkat99** [starkat99/half-rs#66]
Use the 8x x86 SIMD conversions when appropriate, not just the 4x. These are [_mm256_cvtph_ps](https://doc.rust-lang.org/core/arch/x86/fn._mm256_cvtph_ps.html) and [_mm256_cvtps_ph](https://doc.rust-lang.org/core/arch/x86/fn._mm256_cvtps_ph.html). Needs some profiling to determine which to use over the other and in what circumstances, possible that it might be better to use 8x always.

**Comment by Shnatsel** [comment]
The commit that closed this also sped up the fallback codepath, presumably because it's a loop instead of 4 independent calls to the fallback function, so there's less code bloat.

When will a new release with this change ship? We'd like to use it in the `exr` crate: https://github.com/johannesvollmer/exrs/pull/191

**Comment by starkat99** [comment]
Was going to wait until doing some more ARM work, but went ahead and did a 2.2.1 release just now for you.
